credentials:
  usernames:
    restry:
      email: restry@gmail.com
      name: Restry Smith
      password: $2b$12$E2pkuDNB6evJjx5X7aNy5OzOK9T3v4.zLCOpnAtGDTCsPeKmV6LAe # Placeholder for hashed password for 'abc' 
cookie:
  expiry_days: 30
  key: $2b$12$MOcJDbQeWRGKB.Gbh3PlMOz5kZniY712XBArBxX2/ARZJhmzUrrue # Must be string
  name: car_order_identifier
preauthorized:
  emails:
  - michael.keepgoing@gmail.com